name: Tests

on:
  push:
    branches:
      - main

jobs:
  python-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: "3.9.12"
          cache: "pip"
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          nile install
      - name: Run unit tests
        run: pytest tests
  protostar-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install protostar
        run: |
          curl -L https://raw.githubusercontent.com/software-mansion/protostar/master/install.sh | bash
      - name: Update env variables
        run: |
          source /home/runner/.bashrc | bash
      - name: Install protostar dependencies
        run: /home/runner/.protostar/dist/protostar/protostar install
      - name: Run protostar tests
        run: /home/runner/.protostar/dist/protostar/protostar test ./tests --cairo-path lib/cairo_contracts/src
