name: Tests

on:
  push:
    branches:
      - main

jobs:
  python-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: "3.9.12"
          cache: "pip"
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          nile install
      - name: Run unit tests
        run: pytest tests
